# Usar una imagen base de Python
FROM python:3.8-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los scripts y el archivo JSON al contenedor
COPY script_server.py /app/
COPY message_manager.py /app/
COPY chat_thread.py /app/
COPY db_messages.json /app/ 

# Comando para ejecutar el servidor
CMD ["python", "script_server.py"]
